import '../styles/globals.css'
import Header from './Header'
import { Providers } from './providers'
import { getServerSession } from 'next-auth'

export const metadata = {
	title: 'Messenger',
	description: 'Generated by Next.js',
}

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	const session = await getServerSession()
	const header = await Header()

	return (
		<html lang='en'>
			<body>
				{header}
				<Providers session={session}>{children}</Providers>
			</body>
		</html>
	)
}
